import type { ThemeOutput } from "./schema"

export function exportThemeAlgorithmFromOutput(theme: ThemeOutput): string {
  return `/**
 * Generated by Design System Lab.
 *
 * Architecture:
 * Seed Token
 * -> Algorithmic Map Token
 * -> Semantic Token
 * -> Official shadcn Adapter Token
 * -> Design System Lab shadcn Extension Token
 * -> ThemeOutput
 *
 * ThemeSeed is the only editable theme source. Downstream tokens are derived.
 */

import type { ThemeSeed } from "./schema"
import { deriveTheme } from "./derive-theme"

export const themeSeed: ThemeSeed = ${JSON.stringify(theme.seed, null, 2)}

export const theme = deriveTheme(themeSeed)

/**
 * If you copy this file into a different project,
 * also copy the \`lib/theme\` algorithm utilities or replace \`deriveTheme\`
 * with your local implementation.
 */
`
}
