import {
  assertAntdThemeHealth,
  createAntdThemeHealthReport,
} from "./antd-health"
import type {
  AntdThemeAlgorithmName,
  AntdTokens,
  ThemeOutput,
} from "./schema"

function serializeTokens(tokens: AntdTokens): string {
  return JSON.stringify(tokens, null, 2)
}

function serializeAlgorithms(
  algorithms: readonly AntdThemeAlgorithmName[]
): string {
  return algorithms
    .map((algorithm) => `antdTheme.${algorithm}`)
    .join(", ")
}

export function exportAntdThemeTsFromOutput(theme: ThemeOutput): string {
  assertAntdThemeHealth(theme, "Ant Design theme export")
  const health = createAntdThemeHealthReport(theme)
  const adapter = theme.antdTheme

  return `/**
 * Generated by Design System Lab.
 *
 * Ant Design theme architecture:
 * ThemeSeed -> Algorithmic Map Tokens -> Semantic Tokens
 * -> Ant Design ConfigProvider ThemeConfig -> every Ant Design component.
 *
 * Keep the global token layer complete. Add component-level overrides only
 * when a component has a repeated visual concept that global tokens cannot express.
 */

import type { ThemeConfig } from "antd"
import { theme as antdTheme } from "antd"

const lightToken: NonNullable<ThemeConfig["token"]> = ${serializeTokens(
    adapter.light.token
  )}

const darkToken: NonNullable<ThemeConfig["token"]> = ${serializeTokens(
    adapter.dark.token
  )}

export const antdLightTheme: ThemeConfig = {
  algorithm: [${serializeAlgorithms(adapter.light.algorithm)}],
  token: lightToken,
  cssVar: {
    prefix: "${adapter.cssVar.prefix}",
    key: "${adapter.cssVar.lightKey}",
  },
  inherit: true,
}

export const antdDarkTheme: ThemeConfig = {
  algorithm: [${serializeAlgorithms(adapter.dark.algorithm)}],
  token: darkToken,
  cssVar: {
    prefix: "${adapter.cssVar.prefix}",
    key: "${adapter.cssVar.darkKey}",
  },
  inherit: true,
}

export const antdComponentSize = "${adapter.componentSize}" as const

export function getAntdConfigProviderProps(isDark: boolean) {
  return {
    componentSize: antdComponentSize,
    theme: isDark ? antdDarkTheme : antdLightTheme,
  } as const
}

export const antdThemeHealth = ${JSON.stringify(health, null, 2)} as const

/**
 * Root usage:
 *
 * <ConfigProvider {...getAntdConfigProviderProps(isDark)}>
 *   <App>{children}</App>
 * </ConfigProvider>
 *
 * Use App/useApp or component hooks for message, modal, and notification so
 * static feedback APIs receive ConfigProvider theme context.
 */
`
}

export function exportAntdTailwindCssFromOutput(theme: ThemeOutput): string {
  assertAntdThemeHealth(theme, "Ant Design Tailwind bridge export")

  return `/* Generated by Design System Lab */
/* Place after @import "tailwindcss"; in the active global stylesheet. */
/* Ant Design cssVar must stay enabled on the wrapping ConfigProvider. */

/* theme-lab:antd-tailwind:start */
@theme inline {
  /* Color */
  --color-page: var(--ant-color-bg-layout);
  --color-surface: var(--ant-color-bg-container);
  --color-overlay: var(--ant-color-bg-elevated);
  --color-inverse: var(--ant-color-bg-spotlight);
  --color-content: var(--ant-color-text);
  --color-content-secondary: var(--ant-color-text-secondary);
  --color-content-tertiary: var(--ant-color-text-tertiary);
  --color-content-disabled: var(--ant-color-text-quaternary);
  --color-border: var(--ant-color-border);
  --color-border-subtle: var(--ant-color-border-secondary);
  --color-brand: var(--ant-color-primary);
  --color-brand-hover: var(--ant-color-primary-hover);
  --color-brand-active: var(--ant-color-primary-active);
  --color-on-brand: var(--ant-color-text-light-solid);
  --color-success: var(--ant-color-success);
  --color-success-soft: var(--ant-color-success-bg);
  --color-warning: var(--ant-color-warning);
  --color-warning-soft: var(--ant-color-warning-bg);
  --color-info: var(--ant-color-info);
  --color-info-soft: var(--ant-color-info-bg);
  --color-danger: var(--ant-color-error);
  --color-danger-soft: var(--ant-color-error-bg);

  /* Typography */
  --font-sans: var(--ant-font-family);
  --font-mono: var(--ant-font-family-code);
  --text-caption: var(--ant-font-size-sm);
  --text-caption--line-height: var(--ant-line-height-sm);
  --text-body: var(--ant-font-size);
  --text-body--line-height: var(--ant-line-height);
  --text-title: var(--ant-font-size-heading-4);
  --text-title--line-height: var(--ant-line-height-heading-4);
  --text-display: var(--ant-font-size-heading-1);
  --text-display--line-height: var(--ant-line-height-heading-1);

  /* Geometry and density */
  --radius-control: var(--ant-border-radius);
  --radius-card: var(--ant-border-radius-lg);
  --radius-overlay: var(--ant-border-radius-outer);
  --spacing-control-sm: var(--ant-control-height-sm);
  --spacing-control: var(--ant-control-height);
  --spacing-control-lg: var(--ant-control-height-lg);
  --spacing-section: var(--ant-padding-lg);
  --spacing-panel: var(--ant-padding);

  /* Elevation and motion */
  --shadow-card: var(--ant-box-shadow-tertiary);
  --shadow-overlay: var(--ant-box-shadow-secondary);
  --shadow-dialog: var(--ant-box-shadow);
  --duration-fast: var(--ant-motion-duration-fast);
  --duration-base: var(--ant-motion-duration-mid);
  --duration-slow: var(--ant-motion-duration-slow);
}
/* theme-lab:antd-tailwind:end */

/*
 * Example utilities:
 * bg-page text-content
 * bg-surface border-border rounded-card shadow-card
 * bg-brand text-on-brand hover:bg-brand-hover
 * h-control px-panel text-body
 */
`
}
