import type { ThemeOutput } from "./schema"

const algorithmVersions = {
  color: "oklch-seed-v1",
  radius: "ratio-v1",
  density: "density-v1",
  typography: "type-v1",
  elevation: "elevation-v1",
  motion: "motion-v1",
  semantic: "semantic-map-v1",
  shadcn: "shadcn-adapter-v1",
  vibe: "descriptor-v1",
} as const

const themeLabManifestAlgorithmVersion = "theme-lab-seed-algorithm-v1"

function normalizeUserDesignRules(userDesignRules?: string): string {
  return userDesignRules?.trim() ?? ""
}

export const themeLabDesignRuleLibrary = {
  entrypoint: "design-rules/index.json",
  rawEntrypoint:
    "https://raw.githubusercontent.com/Gusgoooo/DesignSystemLab/codex/distributed-design-rules/design-rules/index.json",
  rawBaseUrl:
    "https://raw.githubusercontent.com/Gusgoooo/DesignSystemLab/codex/distributed-design-rules",
  basePath: "design-rules",
  routing:
    "Detect page structure first, load requiredAlways rules, open matched page-structure/block rules, then open only matched component, pattern, and token files from rules[].source. If the local design-rules directory is unavailable, read the raw GitHub rule URLs.",
  readConfirmation:
    "Before editing, list ruleIndexRead, requiredRuleFilesLoaded, matchedRuleFilesLoaded with elementType/source/firstHeading, and missingRuleFiles. Do not claim a rule was applied unless the file was actually opened.",
  files: [
    "design-rules/index.json",
    "design-rules/core/rule-router.md",
    "design-rules/core/ui-normalization.md",
    "design-rules/core/token-binding.md",
    "design-rules/core/token-system.md",
    "design-rules/core/visual-qa.md",
    "design-rules/core/completion-compliance.md",
    "design-rules/core/product-alignment.md",
    "design-rules/blocks/page-shell.md",
    "design-rules/blocks/dashboard.md",
    "design-rules/components/card.md",
    "design-rules/components/table.md",
    "design-rules/components/page-heading.md",
    "design-rules/components/sidebar.md",
    "design-rules/components/actions-and-buttons.md",
    "design-rules/components/filters-and-controls.md",
    "design-rules/components/forms-and-inputs.md",
    "design-rules/components/tabs.md",
    "design-rules/components/overlays.md",
    "design-rules/components/badges-and-alerts.md",
    "design-rules/components/metrics-and-charts.md",
    "design-rules/patterns/page-background.md",
    "design-rules/patterns/states.md",
    "design-rules/patterns/semantic-color.md",
  ],
} as const

export const themeLabAiInstructionTargets = [
  {
    tool: "Claude Code",
    primaryFile: "CLAUDE.md",
    notes: "Use for Claude Code project memory and persistent project instructions.",
  },
  {
    tool: "OpenAI Codex",
    primaryFile: "AGENTS.md",
    notes: "Codex reads AGENTS.md for repository guidance.",
  },
  {
    tool: "Cursor",
    primaryFile: ".cursor/rules/theme-lab.mdc",
    fallbackFile: "AGENTS.md",
    notes: "Use Cursor project rules when present; AGENTS.md is acceptable for cross-agent compatibility.",
  },
  {
    tool: "GitHub Copilot",
    primaryFile: ".github/copilot-instructions.md",
    notes: "Use repository-wide Copilot custom instructions.",
  },
  {
    tool: "Gemini CLI",
    primaryFile: "GEMINI.md",
    notes: "Use Gemini CLI context files.",
  },
  {
    tool: "Windsurf/Cascade",
    primaryFile: ".windsurfrules",
    notes: "Use Windsurf project rules when the project already uses Windsurf.",
  },
  {
    tool: "Qoder",
    primaryFile: "AGENTS.md",
    notes: "Qoder is compatible with AGENTS.md; native Qoder rules may take precedence.",
  },
] as const

export const themeLabTokenContract = {
  allowed: [
    "bg-background",
    "text-foreground",
    "bg-card",
    "text-card-foreground",
    "bg-popover",
    "text-popover-foreground",
    "bg-primary",
    "text-primary-foreground",
    "bg-secondary",
    "text-secondary-foreground",
    "bg-muted",
    "text-muted-foreground",
    "bg-accent",
    "text-accent-foreground",
    "bg-destructive",
    "text-destructive-foreground",
    "bg-sidebar",
    "text-sidebar-foreground",
    "bg-sidebar-primary",
    "text-sidebar-primary-foreground",
    "bg-sidebar-accent",
    "text-sidebar-accent-foreground",
    "border-border",
    "ring-ring",
    "bg-[var(--surface-canvas)]",
    "bg-[var(--surface-panel)]",
    "bg-[var(--surface-raised)]",
    "text-[var(--content-primary)]",
    "text-[var(--content-secondary)]",
    "text-[var(--content-tertiary)]",
    "border-[var(--border-subtle)]",
    "border-[var(--border-default)]",
    "rounded-[var(--radius-control)]",
    "rounded-[var(--radius-card)]",
    "rounded-[var(--radius-panel)]",
    "rounded-[var(--radius)]",
    "h-[var(--control-height-sm)]",
    "h-[var(--control-height-md)]",
    "h-[var(--control-height-lg)]",
    "gap-[var(--section-gap)]",
    "p-[var(--panel-padding)]",
    "[box-shadow:var(--elevation-card)]",
    "[box-shadow:var(--elevation-popover)]",
    "duration-[var(--duration-base)]",
    "ease-[var(--ease-standard)]",
    "bg-success-bg",
    "text-success-foreground",
    "bg-warning-bg",
    "text-warning-foreground",
    "bg-info-bg",
    "text-info-foreground",
    "bg-danger-bg",
    "text-danger-foreground",
    "bg-success",
    "bg-warning",
    "bg-info",
    "bg-danger",
    "bg-chart-1",
    "bg-chart-2",
    "bg-chart-3",
    "bg-chart-4",
    "bg-chart-5",
    "text-chart-1",
    "text-chart-2",
    "text-chart-3",
    "text-chart-4",
    "text-chart-5",
    "border-chart-1",
    "border-chart-2",
    "border-chart-3",
    "border-chart-4",
    "border-chart-5",
  ],
  forbiddenForStructuralUi: [
    "raw Tailwind palette classes",
    "hardcoded hex colors",
    "arbitrary OKLCH values",
    "one-off shadow values",
    "one-off border colors",
    "legacy non-token radius values",
    "arbitrary border-radius values",
    "mixed radius scales",
    "same-role filled background/text pairs such as bg-primary text-primary",
    "missing foreground tokens on filled semantic backgrounds",
    "random gradient utilities",
    "unapproved new color scales beyond the sanctioned --status-* and --chart-1..5 families",
  ],
} as const

export const themeLabAiCodingRules = [
  "Write all AI-facing instructions, theme manifests, vibe descriptors, task packets, and final implementation reports in English.",
  "Read theme-lab.json before UI changes.",
  "Global CSS variables are the runtime source for styling.",
  "One-time prompts are not the source of truth.",
  "Preserve routes, APIs, data loading, state, handlers, forms, validation, permissions, feature flags, and business logic.",
  "Do not scaffold a new app inside an existing project.",
  "Do not create a parallel design system.",
  "Do not install dependencies unless approved.",
  "The exactly-three persistent touchpoints rule applies only to theme contract files; UI normalization may modify existing route, layout, app shell, and component files that are part of the approved normalization plan.",
  "Do not use raw Tailwind palette classes for structural UI.",
  "Do not use hardcoded hex colors for structural UI.",
  "Do not use arbitrary OKLCH values for structural UI.",
  "When changing UI, consume the existing compiled CSS variables and token contract.",
  "Use design-rules/index.json as the distributed design rule router when it exists.",
  "If local design-rules/index.json is unavailable, read the raw GitHub rule index at https://raw.githubusercontent.com/Gusgoooo/DesignSystemLab/codex/distributed-design-rules/design-rules/index.json.",
  "Before UI normalization, first detect page structure, then load requiredAlways rule files, then open only page-structure, block, component, pattern, and token rule files matched from rules[].source or the corresponding raw GitHub URL.",
  "Before editing, output a Rule Read Confirmation listing the exact rule files actually opened, including first headings for matched files.",
  "When changing a route, page, or app-level layout, open design-rules/blocks/page-shell.md or its raw GitHub URL before editing page structure.",
  "When installing or bridging tokens, open design-rules/core/token-system.md or its raw GitHub URL before editing token-bearing UI.",
  "Before final response, open design-rules/core/completion-compliance.md or its raw GitHub URL and verify the task against it.",
  "If the selected scope contains cards, open design-rules/components/card.md or its raw GitHub URL before card UI is changed; do not claim the card rule was applied if the file could not be opened.",
  "If the selected scope contains tables, open design-rules/components/table.md or its raw GitHub URL before table UI is changed; do not claim the table rule was applied if the file could not be opened.",
  "If the selected scope contains forms, inputs, field groups, or validation, open design-rules/components/forms-and-inputs.md or its raw GitHub URL before changing form UI.",
  "If the selected scope contains tabs, segmented controls, view switches, mode switches, status switches, or period switches, open design-rules/components/tabs.md or its raw GitHub URL before changing that single-select UI.",
  "If the selected scope contains dialogs, sheets, drawers, popovers, dropdown menus, command palettes, or contextual menus, open design-rules/components/overlays.md or its raw GitHub URL before changing overlay UI.",
  "If the selected scope contains badges, tags, chips, alerts, notices, banners, toasts, or status indicators, open design-rules/components/badges-and-alerts.md and design-rules/patterns/semantic-color.md or their raw GitHub URLs before changing status or feedback UI.",
  "If the selected scope contains KPI cards, metrics, charts, legends, progress indicators, sparklines, trends, or data series, open design-rules/components/metrics-and-charts.md or its raw GitHub URL before changing analytical UI.",
  "If the selected scope is a standard dashboard, open design-rules/blocks/dashboard.md or its raw GitHub URL; use npx shadcn@latest add dashboard-01 as the default implementation baseline when safe, then map the user's original dashboard modules into the new shell one by one.",
  "If a tool cannot access local files or raw URLs, say so explicitly and ask the user to provide the rule files or accessible raw URLs; do not hallucinate rule contents.",
  "Do not compress all component rules into one prompt; detailed design rules live in separate design-rules/**/*.md files.",
  "If a matching design rule file is missing, make the smallest safe normalization and report the missing rule file.",
  "When asked to redesign, optimize, rebuild, or refactor a selected UI scope, treat it as UI normalization by default rather than a redesign from scratch.",
  "Preserve existing page content, information architecture, workflow order, business rules, routes, APIs, data loading, state, handlers, forms, validation, permissions, feature flags, and domain copy.",
  "Do not discard the old visible UI tree by default; normalize components, repeated style fragments, token usage, spacing, radius, elevation, and states around the existing product structure.",
  "Prefer existing project components and shadcn/ui primitives for controls and repeated patterns when behavior can be preserved.",
  "Use user-authored Theme Lab design rules as the design source; do not browse, import, or imitate external visual references unless the user explicitly asks.",
  "Before editing, identify which user-authored design rule applies to the selected UI pattern; if no rule exists, make the smallest safe normalization and report the missing rule.",
  "Decorative exceptions explicitly defined by user-authored rules may use non-token colors or values only for non-structural ambient layers, never for text, primary surfaces, borders, focus rings, or actionable states.",
  "For plain page canvases, a very subtle page-top ambient wash may be added as a non-structural background layer behind content.",
  "Page-top ambient wash should occupy only the top fifth of the page or viewport, fade fully into bg-background or transparent, and never create layout height or become an interactive layer.",
  "Page-top ambient wash is a decorative exception: it may use non-token colors, opacity, blur, and gradient stops, but all real UI surfaces, text, borders, focus rings, actions, states, radius, and elevation must remain token-bound.",
  "Page-top ambient wash must stay extremely quiet: low opacity, low saturation, high lightness, broad softness, no hard edge, no bokeh, no blobs, no rainbow gradients, and no strong brand-color bands.",
  "Page-top ambient wash must not reduce contrast, tint cards heavily, hide dividers, compete with the page header, affect sidebars by default, or make primary actions less obvious.",
  "Do not use external references unless the user explicitly provides or requests them; never copy brand styling, demo content, paid/proprietary source code, or unrelated product patterns.",
  "Do not merely place shadcn primitives one by one; normalize the existing product UI with complete, behavior-preserving component patterns.",
  "Use one primary user-authored rule or existing local pattern per page or scope; do not mix multiple systems or invented patterns unless the workflow truly requires it.",
  "Do not introduce extra cards, nested panels, borders, shadows, badges, icons, or toolbars just to make the UI look more shadcn.",
  "For dashboards, use the dashboard block only as shell and composition structure; never keep shadcn demo content, fake users, fake teams, sample chart data, sample table rows, placeholder routes, or generic copy.",
  "Dashboard normalization must preserve route URLs, active route logic, API calls, filters, date ranges, chart transforms, table sorting/filtering/pagination/selection, row actions, permissions, refresh behavior, and loading/empty/error states.",
  "Dashboard UI should answer in order: what is happening, what changed, what needs attention, and what the user can do next.",
  "Dashboard sections should have clear jobs: overview summarizes status and trend, charts explain movement or comparison, tables/lists support investigation, activity shows recency, and alerts identify action-needed items.",
  "Preserve any existing information architecture or workflow order that is already clear, and normalize only the problematic visible UI layer around it.",
  "When the selected scope contains a page heading, page header, title/action bar, resource header, detail header, or list header, reuse the Page Heading pattern: left title and metadata facts, right primary and secondary actions, responsive stacking, and mobile More menu for secondary actions.",
  "Page headings should use a responsive layout equivalent to lg:flex lg:items-center lg:justify-between, with a min-w-0 flex-1 title area and a mt-5 action group that aligns on large screens.",
  "Page heading metadata should be compact icon + short text facts below the title, using actual product fields such as status, type, owner, team, location, date, amount, workspace, lifecycle stage, last updated, or due date.",
  "Do not copy page heading demo content such as job titles, fake locations, fake salaries, or fake dates; preserve the product's real title, metadata, breadcrumbs, status, filters, and action semantics.",
  "Do not add @heroicons/react or @headlessui/react for page headings unless the project already uses them; map icons to the existing icon library and menus/actions to existing shadcn or project components.",
  "Convert page heading raw sample colors to Theme Lab tokens: text-foreground, text-muted-foreground, bg-background, bg-primary text-primary-foreground, border-border, ring-ring, and existing button variants.",
  "Keep page headings unframed by default; do not wrap the whole heading in a decorative card unless the product already uses framed headers.",
  "Page heading actions must preserve behavior: keep the primary action visible, make secondary actions quieter, and collapse secondary actions into a More dropdown on small screens when horizontal space is limited.",
  "Page headings must avoid overflow: long titles should use min-w-0, truncate, wrapping, or responsive stacking, and actions must not collide with the title.",
  "Before final report, verify that the normalized UI is calmer, clearer, more readable, and more internally consistent than the previous UI.",
  "Normalize bespoke, non-shadcn, or non-shadcn-like visible components inside the selected scope when behavior can be preserved.",
  "If a needed shadcn component file is missing, inspect the existing shadcn setup and add local component files through the project's established shadcn workflow when that does not introduce new production dependencies.",
  "Reconnect existing API calls, data loaders, mutations, event handlers, validation, navigation, permissions, and state to the normalized UI.",
  "When the selected page or product scope contains a sidebar, include the complete sidebar in the UI normalization scope; do not polish only the main content while leaving the old bespoke sidebar in place.",
  "When a sidebar is detected, do not ask an open-ended question such as whether the sidebar should also be changed; include it by default in the normalization plan.",
  "If a sidebar is detected, the execution plan must include a Direct Confirmation line: The selected scope contains a sidebar, so sidebar normalization/replacement is included by default. Please confirm the full plan if you want me to proceed.",
  "For sidebar replacement, the user explicitly approves the official shadcn sidebar blocks reference: https://ui.shadcn.com/blocks/sidebar.",
  "Choose the closest matching shadcn sidebar block based on the existing navigation structure, density, grouping, collapse behavior, account/workspace switchers, search, badges, nested groups, and responsive behavior.",
  "If no shadcn sidebar block clearly matches the existing navigation structure, install the fallback block with npx shadcn@latest add sidebar-08, then adapt it to the existing routes, labels, groups, data, permissions, and active states.",
  "Before running a shadcn sidebar command, inspect components.json, the existing components/ui directory, aliases, package manager, and whether components/ui/sidebar already exists; do not overwrite unrelated files.",
  "Do not copy shadcn demo content, fake teams, fake projects, fake users, or placeholder routes into the product; the block is only an implementation pattern.",
  "Sidebar replacement must preserve existing route URLs, active route logic, permissions, badges/counts, account or workspace context, user menu actions, collapse behavior, and responsive behavior unless the user explicitly changes them.",
  "Sidebar replacement must use shadcn sidebar primitives such as SidebarProvider, Sidebar, SidebarInset, SidebarHeader, SidebarContent, SidebarGroup, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarFooter, SidebarRail, and SidebarTrigger when they fit the project setup.",
  "Sidebar styling must connect to Theme Lab tokens: use bg-sidebar text-sidebar-foreground, bg-sidebar-primary text-sidebar-primary-foreground, bg-sidebar-accent text-sidebar-accent-foreground, border-sidebar-border or border-border, ring-sidebar-ring or ring-ring, and token-backed radius, spacing, and elevation where applicable.",
  "After replacing a sidebar, verify active, hover, focus-visible, selected, collapsed, expanded, mobile sheet/drawer, disabled, loading, and permission-hidden states.",
  "For long-term projects, treat the work as product-wide UI alignment: preserve existing page workflows while unifying component grammar, page-header rhythm, content width system, action placement, state design, and responsive behavior.",
  "Do not deliver isolated page makeovers in a long-term project; similar page types must share component and token patterns while preserving their workflows.",
  "Do not produce a generic shadcn SaaS look; use shadcn primitives as implementation materials while creating product-specific rhythm through page headers, density, surface contrast, card grouping, navigation emphasis, primary action placement, state tone, and restrained brand color.",
  "Before the final report, compare normalized UI against previous UI and explicitly report preserved content/workflow, unified component patterns, reduced UI debt, semantic token pairs checked, responsive states checked, and pages still needing alignment.",
  "Normalize component hierarchy, responsive behavior, and interaction states before or while applying tokens.",
  "Reject token-only outcomes when obvious ad hoc controls or inconsistent component patterns remain.",
  "Cards and tables must follow their distributed rule files; do not rely on summarized card/table guidance embedded in the prompt.",
  "Forms, tabs, overlays, badges/alerts, and metrics/charts must follow their distributed rule files; do not rely on generic shadcn defaults alone when those element types are present.",
  "For single-select UI that switches a view, filter, mode, status, period, or section, use shadcn Tabs rather than a row of Button components.",
  "Do not express selected state by making one option a primary button and the remaining options secondary, outline, or ghost buttons; that confuses action hierarchy with selection state.",
  "Use Button components for commands such as create, save, export, delete, refresh, submit, open, and cancel; use Tabs for single-select switching; use RadioGroup only for true form-field choices submitted as data.",
  "When tabs, buttons, selects, search inputs, date ranges, or view controls appear in the same horizontal row, make them share the same token-backed control height.",
  "In horizontal control rows, keep filters, search, tabs, view switches, status switches, sort, and date ranges left-aligned; keep operation buttons such as create, export, refresh, save, apply, delete, and bulk actions right-aligned on desktop.",
  "Do not mix visibly different heights for TabsList, TabsTrigger, Input, SelectTrigger, Button, DropdownMenuTrigger, and date range triggers in the same toolbar unless the controls belong to separate visual regions.",
  "When card or table UI is present, the final report must list the exact local rule file or raw GitHub URL opened for the card/table rule.",
  "For long-term projects, land the persistent token contract through exactly the three conceptual touchpoints: existing global CSS token block, theme-lab.json, and the target tool's native AI instruction file.",
  "Resolve the AI instruction target by tool: Claude Code uses CLAUDE.md; Codex and generic agents use AGENTS.md; Cursor uses .cursor/rules/theme-lab.mdc when Cursor rules exist; GitHub Copilot uses .github/copilot-instructions.md; Gemini CLI uses GEMINI.md; Windsurf uses .windsurfrules; Qoder can use AGENTS.md.",
  "Do not create every supported AI instruction file by default; update the detected or requested tool-native file, and create multiple instruction files only when the user explicitly requests multi-tool compatibility.",
  "Do not create or update local design-rules/ files by default; read distributed rules from raw GitHub URLs unless the user explicitly asks to install the rule library locally.",
  "For one-shot selected-scope optimization, create or reuse a minimal but complete token bridge covering surfaces, foregrounds, borders, focus rings, radius, density, elevation, states, and motion for the changed UI.",
  "Do not ship partial token setup such as primary/background only; incomplete token systems cause invisible text, mismatched radius, unsafe focus states, and inconsistent cards.",
  "Semantic token pairs are mandatory for filled surfaces: use bg-primary text-primary-foreground, bg-secondary text-secondary-foreground, bg-card text-card-foreground, bg-popover text-popover-foreground, bg-accent text-accent-foreground, bg-destructive text-destructive-foreground, bg-sidebar text-sidebar-foreground, bg-sidebar-primary text-sidebar-primary-foreground, and bg-sidebar-accent text-sidebar-accent-foreground.",
  "Never use same-role filled background/text pairs such as bg-primary text-primary, bg-secondary text-secondary, bg-accent text-accent, bg-destructive text-destructive, bg-card text-card, or bg-popover text-popover.",
  "Before final report, audit changed product UI for raw palette classes, hardcoded color functions, legacy radius/shadow utilities, same-role filled surface pairs, missing foreground tokens, and missing focus-visible rings.",
  "Token binding is incomplete if old radius or shadow values remain in normalized product components, if filled actions have invisible text, or if token audit hits are ignored silently.",
  "When changing theme direction, update the seed in theme-lab.json, then regenerate compiled CSS variables through Theme Lab or the available theme generation pipeline.",
] as const

export function exportPresetJsonFromOutput(theme: ThemeOutput): string {
  return JSON.stringify(
    {
      version: "0.1.0",
      name: theme.vibe.name,
      seed: theme.seed,
      algorithms: algorithmVersions,
      tokens: {
        map: theme.mapTokens,
        semantic: theme.semanticTokens,
        darkSemantic: theme.darkSemanticTokens,
        shadcn: theme.shadcnTokens,
        darkShadcn: theme.darkShadcnTokens,
      },
      vibe: theme.vibe,
    },
    null,
    2
  )
}

export function exportVibeJsonFromOutput(theme: ThemeOutput): string {
  return JSON.stringify(
    {
      name: theme.vibe.name,
      keywords: theme.vibe.keywords,
      visualContract: theme.vibe.visualContract,
    },
    null,
    2
  )
}

export function exportThemeLabManifestJsonFromOutput(
  theme: ThemeOutput,
  userDesignRules?: string
): string {
  const normalizedUserDesignRules = normalizeUserDesignRules(userDesignRules)

  return JSON.stringify(
    {
      schemaVersion: 1,
      kind: "theme-lab-manifest",
      theme: {
        name: theme.vibe.name,
        sourceOfTruth: "seed-and-algorithm",
        algorithmVersion: themeLabManifestAlgorithmVersion,
        cssTarget: "existing-global-css-marker-block",
        generatedAt: new Date().toISOString(),
        seed: theme.seed,
      },
      vibe: {
        summary: theme.vibe.visualContract.summary,
        keywords: theme.vibe.keywords,
        avoid: theme.vibe.visualContract.avoid,
      },
      tokenContract: themeLabTokenContract,
      designRuleLibrary: themeLabDesignRuleLibrary,
      userAuthoredDesignRules: normalizedUserDesignRules
        ? {
            source: "Theme Lab export panel",
            format: "markdown",
            body: normalizedUserDesignRules,
          }
        : undefined,
      aiCoding: {
        defaultProjectMode: "existing-product-project",
        instructionTargets: themeLabAiInstructionTargets,
        rules: themeLabAiCodingRules,
      },
    },
    null,
    2
  )
}
