export const registryPageTypes = [
  "auto",
  "dashboard",
  "resource-index",
  "settings",
  "form-flow",
  "auth",
  "ai-command",
  "docs-spec",
  "detail",
  "marketing",
] as const

export type RegistryPageType = (typeof registryPageTypes)[number]
export type ResolvedRegistryPageType = Exclude<RegistryPageType, "auto">

export type RegistryProjectMode = "existing-product" | "greenfield"
export type RegistryPrimitiveEngine = "radix" | "base-ui" | "unknown"
export type RegistryPrimitivePolicy = "auto" | "radix" | "base-ui"
export type RegistryCapabilityKind = "registry:block" | "registry:bundle"
export type RegistrySourceTier =
  | "official"
  | "approved-community"
  | "project-private"
export type RegistryCapabilityRisk = "low" | "review" | "high"

export type RegistryPageProfile = {
  pageType: ResolvedRegistryPageType
  requiredSlots: readonly string[]
  criticalSlots: readonly string[]
  requiredStates: readonly string[]
}

export type RegistryCapabilityItem = {
  id: string
  title: string
  description: string
  kind: RegistryCapabilityKind
  compositionMode: "adapt-block" | "compose-primitives"
  namespace: string
  installItems: readonly string[]
  sourceTier: RegistrySourceTier
  sourceUrl: string
  verifiedAt: string
  primitiveEngines: readonly Exclude<RegistryPrimitiveEngine, "unknown">[]
  pageTypes: readonly ResolvedRegistryPageType[]
  slots: readonly string[]
  states: readonly string[]
  requiredPrimitives: readonly string[]
  tokenRoles: readonly string[]
  risk: RegistryCapabilityRisk
  notes?: string
}

export const registryPageProfiles: Record<
  ResolvedRegistryPageType,
  RegistryPageProfile
> = {
  dashboard: {
    pageType: "dashboard",
    requiredSlots: [
      "page.shell",
      "navigation.sidebar",
      "page.heading",
      "metric.summary",
      "data.chart",
      "data.table",
      "state.feedback",
    ],
    criticalSlots: ["page.shell", "metric.summary", "data.table"],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
    ],
  },
  "resource-index": {
    pageType: "resource-index",
    requiredSlots: [
      "page.shell",
      "page.heading",
      "data.toolbar",
      "data.table",
      "data.row-actions",
      "state.feedback",
    ],
    criticalSlots: ["data.toolbar", "data.table", "data.row-actions"],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
      "selected",
    ],
  },
  settings: {
    pageType: "settings",
    requiredSlots: [
      "page.shell",
      "page.heading",
      "form.field-group",
      "form.validation",
      "action.save-reset",
      "state.feedback",
    ],
    criticalSlots: [
      "form.field-group",
      "form.validation",
      "action.save-reset",
    ],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "disabled",
      "loading",
      "error",
      "success",
    ],
  },
  "form-flow": {
    pageType: "form-flow",
    requiredSlots: [
      "page.shell",
      "form.heading",
      "form.field-group",
      "form.validation",
      "action.submit",
      "state.feedback",
    ],
    criticalSlots: [
      "form.field-group",
      "form.validation",
      "action.submit",
    ],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "disabled",
      "loading",
      "error",
      "success",
    ],
  },
  auth: {
    pageType: "auth",
    requiredSlots: [
      "page.shell",
      "auth.heading",
      "auth.credentials",
      "auth.recovery",
      "action.submit",
      "form.validation",
      "state.feedback",
    ],
    criticalSlots: ["auth.credentials", "action.submit", "form.validation"],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "disabled",
      "loading",
      "error",
    ],
  },
  "ai-command": {
    pageType: "ai-command",
    requiredSlots: [
      "page.shell",
      "navigation.context",
      "ai.thread",
      "ai.composer",
      "ai.tool-state",
      "state.feedback",
    ],
    criticalSlots: ["ai.thread", "ai.composer", "ai.tool-state"],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
      "streaming",
    ],
  },
  "docs-spec": {
    pageType: "docs-spec",
    requiredSlots: [
      "page.shell",
      "navigation.section",
      "docs.content",
      "docs.code-table",
      "docs.detail-overlay",
      "state.feedback",
    ],
    criticalSlots: ["navigation.section", "docs.content"],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
    ],
  },
  detail: {
    pageType: "detail",
    requiredSlots: [
      "page.shell",
      "page.heading",
      "detail.summary",
      "detail.sections",
      "detail.actions",
      "state.feedback",
    ],
    criticalSlots: ["page.heading", "detail.summary", "detail.actions"],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
      "permission-hidden",
    ],
  },
  marketing: {
    pageType: "marketing",
    requiredSlots: [
      "page.shell",
      "marketing.hero",
      "marketing.proof",
      "marketing.offer",
      "marketing.cta",
      "state.feedback",
    ],
    criticalSlots: ["marketing.hero", "marketing.offer", "marketing.cta"],
    requiredStates: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "error",
    ],
  },
}

const officialComponentsUrl = "https://ui.shadcn.com/docs/components"

export const registryCapabilityItems: readonly RegistryCapabilityItem[] = [
  {
    id: "shadcn/dashboard-01",
    title: "Dashboard 01",
    description: "Dashboard shell with sidebar, summary cards, chart, and table.",
    kind: "registry:block",
    compositionMode: "adapt-block",
    namespace: "@shadcn",
    installItems: ["dashboard-01"],
    sourceTier: "official",
    sourceUrl: "https://ui.shadcn.com/blocks?category=dashboard",
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["dashboard"],
    slots: [
      "page.shell",
      "navigation.sidebar",
      "page.heading",
      "metric.summary",
      "data.chart",
      "data.table",
      "data.toolbar",
    ],
    states: ["responsive", "focus-visible", "keyboard", "selected"],
    requiredPrimitives: [
      "sidebar",
      "breadcrumb",
      "card",
      "chart",
      "table",
      "tabs",
    ],
    tokenRoles: [
      "page.canvas",
      "navigation.sidebar",
      "card.raised",
      "data.category",
      "state.interactive",
    ],
    risk: "low",
    notes: "Replace all demonstration data, routes, and labels with the product model.",
  },
  {
    id: "shadcn/sidebar-07",
    title: "Sidebar 07",
    description: "Application shell with grouped navigation and workspace context.",
    kind: "registry:block",
    compositionMode: "adapt-block",
    namespace: "@shadcn",
    installItems: ["sidebar-07"],
    sourceTier: "official",
    sourceUrl: "https://ui.shadcn.com/blocks/sidebar",
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["dashboard", "resource-index", "settings", "detail"],
    slots: [
      "page.shell",
      "navigation.sidebar",
      "navigation.context",
      "navigation.section",
      "page.heading",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "selected",
      "collapsed-navigation",
    ],
    requiredPrimitives: ["sidebar", "dropdown-menu", "breadcrumb", "avatar"],
    tokenRoles: [
      "page.canvas",
      "navigation.sidebar",
      "navigation.sidebar-active",
      "state.interactive",
    ],
    risk: "low",
  },
  {
    id: "shadcn/sidebar-08",
    title: "Sidebar 08",
    description: "Collapsible application sidebar with nested navigation.",
    kind: "registry:block",
    compositionMode: "adapt-block",
    namespace: "@shadcn",
    installItems: ["sidebar-08"],
    sourceTier: "official",
    sourceUrl: "https://ui.shadcn.com/blocks/sidebar",
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: [
      "dashboard",
      "resource-index",
      "settings",
      "ai-command",
      "detail",
    ],
    slots: [
      "page.shell",
      "navigation.sidebar",
      "navigation.context",
      "navigation.section",
      "page.heading",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "selected",
      "collapsed-navigation",
    ],
    requiredPrimitives: ["sidebar", "collapsible", "dropdown-menu", "avatar"],
    tokenRoles: [
      "page.canvas",
      "navigation.sidebar",
      "navigation.sidebar-active",
      "state.interactive",
    ],
    risk: "low",
  },
  {
    id: "shadcn/sidebar-16",
    title: "Sidebar 16",
    description: "Application sidebar paired with a sticky site header.",
    kind: "registry:block",
    compositionMode: "adapt-block",
    namespace: "@shadcn",
    installItems: ["sidebar-16"],
    sourceTier: "official",
    sourceUrl: "https://ui.shadcn.com/blocks/sidebar",
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["resource-index", "docs-spec", "detail"],
    slots: [
      "page.shell",
      "navigation.sidebar",
      "navigation.section",
      "page.heading",
      "docs.content",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "selected",
      "collapsed-navigation",
    ],
    requiredPrimitives: ["sidebar", "breadcrumb", "input", "dropdown-menu"],
    tokenRoles: [
      "page.canvas",
      "navigation.sidebar",
      "navigation.sidebar-active",
      "control.input",
    ],
    risk: "low",
  },
  {
    id: "shadcn/login-01",
    title: "Login 01",
    description: "Compact authentication form baseline.",
    kind: "registry:block",
    compositionMode: "adapt-block",
    namespace: "@shadcn",
    installItems: ["login-01"],
    sourceTier: "official",
    sourceUrl: "https://ui.shadcn.com/blocks/authentication",
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["auth", "form-flow"],
    slots: [
      "page.shell",
      "auth.heading",
      "auth.credentials",
      "auth.recovery",
      "form.heading",
      "form.field-group",
      "form.validation",
      "action.submit",
    ],
    states: ["responsive", "focus-visible", "keyboard", "disabled"],
    requiredPrimitives: ["button", "card", "input", "label"],
    tokenRoles: [
      "page.canvas",
      "card.raised",
      "control.input",
      "action.primary",
    ],
    risk: "low",
  },
  {
    id: "shadcn/login-03",
    title: "Login 03",
    description: "Authentication form on a muted application surface.",
    kind: "registry:block",
    compositionMode: "adapt-block",
    namespace: "@shadcn",
    installItems: ["login-03"],
    sourceTier: "official",
    sourceUrl: "https://ui.shadcn.com/blocks/authentication",
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["auth", "form-flow"],
    slots: [
      "page.shell",
      "auth.heading",
      "auth.credentials",
      "auth.recovery",
      "form.heading",
      "form.field-group",
      "form.validation",
      "action.submit",
      "state.feedback",
    ],
    states: ["responsive", "focus-visible", "keyboard", "disabled"],
    requiredPrimitives: ["button", "input", "label", "separator"],
    tokenRoles: [
      "page.canvas",
      "content.muted",
      "control.input",
      "action.primary",
    ],
    risk: "low",
  },
  {
    id: "shadcn/login-04",
    title: "Login 04",
    description: "Authentication form with a product image region.",
    kind: "registry:block",
    compositionMode: "adapt-block",
    namespace: "@shadcn",
    installItems: ["login-04"],
    sourceTier: "official",
    sourceUrl: "https://ui.shadcn.com/blocks/authentication",
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["auth"],
    slots: [
      "page.shell",
      "auth.heading",
      "auth.credentials",
      "auth.recovery",
      "auth.product-media",
      "form.validation",
      "action.submit",
    ],
    states: ["responsive", "focus-visible", "keyboard", "disabled"],
    requiredPrimitives: ["button", "input", "label"],
    tokenRoles: ["page.canvas", "control.input", "action.primary"],
    risk: "review",
    notes: "Use only when an inspectable product image asset is available.",
  },
  {
    id: "shadcn/resource-index-primitives",
    title: "Resource Index Primitive Bundle",
    description: "Official primitives for searchable, selectable resource lists.",
    kind: "registry:bundle",
    compositionMode: "compose-primitives",
    namespace: "@shadcn",
    installItems: [
      "table",
      "input",
      "select",
      "checkbox",
      "dropdown-menu",
      "pagination",
      "skeleton",
      "alert",
    ],
    sourceTier: "official",
    sourceUrl: officialComponentsUrl,
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["resource-index"],
    slots: [
      "page.heading",
      "data.toolbar",
      "data.table",
      "data.row-actions",
      "state.feedback",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
      "selected",
    ],
    requiredPrimitives: [
      "table",
      "input",
      "select",
      "checkbox",
      "dropdown-menu",
      "pagination",
      "skeleton",
      "alert",
    ],
    tokenRoles: [
      "page.canvas",
      "control.input",
      "state.interactive",
      "content.muted",
      "overlay.floating",
    ],
    risk: "low",
  },
  {
    id: "shadcn/settings-primitives",
    title: "Settings Primitive Bundle",
    description: "Official form primitives for grouped, validated settings.",
    kind: "registry:bundle",
    compositionMode: "compose-primitives",
    namespace: "@shadcn",
    installItems: [
      "form",
      "input",
      "label",
      "select",
      "switch",
      "button",
      "separator",
      "alert",
    ],
    sourceTier: "official",
    sourceUrl: officialComponentsUrl,
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["settings", "form-flow"],
    slots: [
      "page.heading",
      "form.heading",
      "form.field-group",
      "form.validation",
      "action.save-reset",
      "action.submit",
      "state.feedback",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "disabled",
      "loading",
      "error",
      "success",
    ],
    requiredPrimitives: [
      "form",
      "input",
      "label",
      "select",
      "switch",
      "button",
      "separator",
      "alert",
    ],
    tokenRoles: [
      "page.canvas",
      "control.input",
      "action.primary",
      "action.secondary",
      "feedback.status-soft",
    ],
    risk: "low",
  },
  {
    id: "shadcn/ai-command-primitives",
    title: "AI Command Primitive Bundle",
    description: "Official primitives for threads, composers, and tool feedback.",
    kind: "registry:bundle",
    compositionMode: "compose-primitives",
    namespace: "@shadcn",
    installItems: [
      "scroll-area",
      "textarea",
      "button",
      "avatar",
      "dropdown-menu",
      "tooltip",
      "sheet",
      "skeleton",
      "alert",
    ],
    sourceTier: "official",
    sourceUrl: officialComponentsUrl,
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["ai-command"],
    slots: [
      "navigation.context",
      "ai.thread",
      "ai.composer",
      "ai.tool-state",
      "state.feedback",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
      "streaming",
    ],
    requiredPrimitives: [
      "scroll-area",
      "textarea",
      "button",
      "avatar",
      "dropdown-menu",
      "tooltip",
      "sheet",
      "skeleton",
      "alert",
    ],
    tokenRoles: [
      "page.canvas",
      "control.input",
      "action.primary",
      "overlay.floating",
      "content.muted",
    ],
    risk: "low",
    notes: "Preserve the project's streaming, persistence, tool-call, and model logic.",
  },
  {
    id: "shadcn/docs-detail-primitives",
    title: "Docs and Detail Primitive Bundle",
    description: "Official primitives for section navigation and inspectable detail.",
    kind: "registry:bundle",
    compositionMode: "compose-primitives",
    namespace: "@shadcn",
    installItems: [
      "breadcrumb",
      "tabs",
      "scroll-area",
      "table",
      "sheet",
      "dialog",
      "separator",
      "skeleton",
      "alert",
    ],
    sourceTier: "official",
    sourceUrl: officialComponentsUrl,
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["docs-spec", "detail"],
    slots: [
      "page.heading",
      "navigation.section",
      "docs.content",
      "docs.code-table",
      "docs.detail-overlay",
      "detail.summary",
      "detail.sections",
      "detail.actions",
      "state.feedback",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "empty",
      "error",
      "permission-hidden",
    ],
    requiredPrimitives: [
      "breadcrumb",
      "tabs",
      "scroll-area",
      "table",
      "sheet",
      "dialog",
      "separator",
      "skeleton",
      "alert",
    ],
    tokenRoles: [
      "page.canvas",
      "card.raised",
      "overlay.floating",
      "state.interactive",
      "content.muted",
    ],
    risk: "low",
  },
  {
    id: "shadcn/marketing-primitives",
    title: "Marketing Primitive Bundle",
    description: "Official primitives for product offers, proof, and conversion actions.",
    kind: "registry:bundle",
    compositionMode: "compose-primitives",
    namespace: "@shadcn",
    installItems: [
      "navigation-menu",
      "button",
      "card",
      "accordion",
      "dialog",
      "sheet",
      "skeleton",
      "alert",
    ],
    sourceTier: "official",
    sourceUrl: officialComponentsUrl,
    verifiedAt: "2026-07-10",
    primitiveEngines: ["radix", "base-ui"],
    pageTypes: ["marketing"],
    slots: [
      "page.shell",
      "marketing.hero",
      "marketing.proof",
      "marketing.offer",
      "marketing.cta",
      "state.feedback",
    ],
    states: [
      "responsive",
      "focus-visible",
      "keyboard",
      "loading",
      "error",
    ],
    requiredPrimitives: [
      "navigation-menu",
      "button",
      "card",
      "accordion",
      "dialog",
      "sheet",
      "skeleton",
      "alert",
    ],
    tokenRoles: [
      "page.canvas",
      "card.raised",
      "action.primary",
      "action.secondary",
      "overlay.floating",
    ],
    risk: "review",
    notes: "A primitive bundle is not a visual reference; product media and composition still require product-specific evidence.",
  },
]

export const registryResolverWeights = {
  pageTypeFit: 35,
  primitiveCompatibility: 25,
  slotCoverage: 20,
  stateCoverage: 10,
  sourceRisk: 10,
} as const

export const registryInstallDiffGate = {
  version: "shadcn-cli-v4-diff-gate-v1",
  required: true,
  publicApi: {
    discovery: "searchRegistries",
    inspect: "getRegistryItems",
    dependencyResolution: "resolveRegistryItems",
    validation: ["registryItemSchema", "configSchema"],
  },
  cliSequence: [
    "npx shadcn@latest view <items>",
    "npx shadcn@latest add <items> --dry-run",
    "npx shadcn@latest add <items> --diff",
    "npx shadcn@latest add <items>",
  ],
  requiredEvidenceBeforeInstall: [
    "resolved registry namespace and item version/source",
    "dependency and registryDependency tree",
    "file-by-file add/modify/conflict list",
    "CSS variable and dependency changes",
    "mapping from existing product logic to registry slots",
    "mapping from registry slots to semantic token roles",
  ],
  hardStops: [
    "components.json cannot be parsed or registry authentication is missing",
    "primitive engine conflicts with the existing project",
    "the install would overwrite edited project components without a merge plan",
    "the candidate drops routes, handlers, validation, permissions, data, or responsive behavior",
    "demo data, placeholder routes, or unrelated theme variables would be installed",
    "critical page slots are missing and no explicit composition plan exists",
  ],
  installPolicy: [
    "never use --overwrite as the default",
    "do not skip confirmation before the diff is reviewed",
    "install only items missing from the current project",
    "merge compatible local changes instead of replacing useful public APIs",
    "run token, type, build, responsive, and interaction checks after installation",
  ],
} as const

export const registryResolverContract = {
  version: "registry-resolver-v1",
  coverageGate: {
    measurement:
      "Count owned, themeable UI responsibilities in the approved scope, not raw DOM nodes.",
    targetRatio: 1,
    minimumRatio: 0.8,
    coveredBy: [
      "compatible existing shadcn component using the detected primitive engine",
      "selected registry block or primitive bundle",
      "small product-specific leaf composed from approved registry primitives",
    ],
    allowedExclusions: [
      "third-party editor, chart, map, canvas, or media internals that cannot consume project components",
      "browser-native controls whose visible shell is already token-bound",
      "legacy workflow region outside the user-approved scope",
    ],
    requirements: [
      "all included UI is bound to the shared semantic token contract",
      "every exclusion records owner, reason, and containment boundary",
      "no parallel base component system remains inside the approved scope",
      "below 80 percent is blocked unless the user narrows the approved scope",
    ],
  },
  catalogPolicy: [
    "start with the audited official capability index",
    "augment it with namespaces configured in components.json",
    "allow approved community or project-private items only when capability metadata is available",
    "do not treat a visual gallery entry as an installable capability until its dependency and file trees resolve",
  ],
  primitivePolicy: {
    existingProduct:
      "Detect and preserve the current Radix or Base UI engine. Do not migrate primitive engines as part of theme application.",
    greenfield:
      "Use Radix when no primitive engine exists and the user has not selected Base UI explicitly.",
    compatibility:
      "Official shadcn blocks that support both engines remain eligible while components.json is being inspected.",
  },
  scoring: {
    total: 100,
    weights: registryResolverWeights,
    minimumRecommendationScore: 70,
    tieBreakers: [
      "higher critical-slot coverage",
      "existing installed compatible item",
      "official source tier",
      "lower overwrite risk",
      "lexicographically smaller capability id for deterministic output",
    ],
  },
  runtimeDiscovery: [
    "parse components.json and package metadata",
    "detect Radix, Base UI, installed shadcn primitives, aliases, and configured registry namespaces",
    "search configured registries by page job and required slots",
    "fetch candidate item metadata and resolve registry dependencies",
    "normalize candidates into the capability schema and score them",
    "run the install diff gate before any file write",
  ],
  requiredCapabilityMetadata: [
    "pageTypes",
    "primitiveEngines",
    "slots",
    "states",
    "requiredPrimitives",
    "tokenRoles",
    "sourceTier",
    "risk",
  ],
  capabilityIndex: {
    version: "registry-capability-index-v1",
    verifiedAt: "2026-07-10",
    items: registryCapabilityItems.map((item) => ({
      id: item.id,
      kind: item.kind,
      compositionMode: item.compositionMode,
      namespace: item.namespace,
      installItems: item.installItems,
      sourceTier: item.sourceTier,
      sourceUrl: item.sourceUrl,
      primitiveEngines: item.primitiveEngines,
      pageTypes: item.pageTypes,
      slots: item.slots,
      states: item.states,
      tokenRoles: item.tokenRoles,
      risk: item.risk,
    })),
  },
  diffGate: registryInstallDiffGate,
} as const
